baseURL = "https://ericpena.github.io/"
languageCode = "en-us"
title = "Eric Peña"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
# publishDir="docs"
disableKinds = ["taxonomy", "taxonomyTerm"]
uglyURLs = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["RSS"]
